---
- name: Create the Soularr folder
  file:
    path: "{{ docker_dir }}/soularr"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Make sure that slskd container is created and running
  docker_container:
    name: soularr
    image: mrusse08/soularr:latest
    pull: true
    networks:
      - name: "{{ slskd_network_name }}"
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      SLSKD_REMOTE_CONFIGURATION: "true"
      SLSKD_SLSK_PROXY_ENABLED: "true"
      SLSKD_SLSK_PROXY_ADDRESS: "{{ deluge_container_name }}"
      SLSKD_SLSK_PROXY_PORT: "9118"
      SLSKD_DOWNLOADS_DIR: "/downloads"
      SLSKD_INCOMPLETE_DIR: "/incomplete"
    user: "{{ guid }}:{{ guid }}"
    volumes:
      - "{{ mergerfs_root }}/Downloads/slskd_completed:/downloads"
      - "{{ docker_dir }}/soularr:/data"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ slskd_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ slskd_dashboard_url }}"
