---
- name: Create the necessary Healthchecks folder
  file:
    path: "{{ docker_dir }}/{{ healthchecks_container_name }}/config"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0750"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that Healthchecks container is created and running
  community.docker.docker_container:
    name: "{{ healthchecks_container_name }}"
    image: lscr.io/linuxserver/healthchecks:latest
    pull: true
    networks:
      - name: "{{ healthchecks_network_name }}"
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      SITE_ROOT: https://healthchecks.{{ host_local }}
      SITE_NAME: CataFalco
      SUPERUSER_EMAIL: "{{ email }}"
      SUPERUSER_PASSWORD: "{{ healthchecks_password }}"
      DEFAULT_FROM_EMAIL: "{{ email_login }}"
      EMAIL_HOST: "{{ email_smtp_host }}"
      EMAIL_HOST_USER: "{{ email_login }}"
      EMAIL_HOST_PASSWORD: "{{ email_password }}"
      EMAIL_USE_TLS: "True"
      REGISTRATION_OPEN: "False"
      SITE_LOGO_URL: "https://{{ host_local }}/assets/tools/homer-icons/logo.png"
      DEBUG: "False"
    volumes:
      - "{{ docker_dir }}/{{ healthchecks_container_name }}/config:/config"
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ healthchecks_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ healthchecks_dashboard_url }}"
    restart_policy: unless-stopped

- name: Install the SWAG config files
  template:
    src: "{{ healthchecks_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ healthchecks_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
