# References:
#  * https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker
#  * https://hub.docker.com/r/automaticrippingmachine/automatic-ripping-machine
#
# Notes:
# Run `lsscsi -g`, identify optical device and mount both sr/sg
---
- name: Create the necessary ARM folder
  file:
    path: "{{ docker_dir }}/{{ arm_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Copy the main ARM config
  copy:
    src: roles/{{ arm_container_name }}/files/arm.yaml
    dest: "{{ docker_dir }}/{{ arm_container_name }}/config/arm.yaml"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Copy HandBrake custom presets
  copy:
    src: roles/{{ arm_container_name }}/files/handbrake-presets/HQ-576p-x264-crf20.json
    dest: "{{ docker_dir }}/{{ arm_container_name }}/config/HQ-576p-x264-crf20.json"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Make sure that ARM container is created and running
  docker_container:
    name: "{{ arm_container_name }}"
    image: automaticrippingmachine/automatic-ripping-machine:latest
    pull: true
    networks:
      - name: swag_internal_network
    privileged: true
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg4:/dev/sg4
    state: started
    env:
      ARM_UID: "{{ guid }}"
      ARM_GID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ arm_container_name }}/config:/etc/arm/config"
      - "{{ docker_dir }}/{{ arm_container_name }}/db:/home/arm/db"
      - "{{ cache_root }}/Downloads/arm_raw:/home/arm/media/raw"
      - "{{ cache_root }}/Downloads/arm_transcode:/home/arm/media/transcode"
      - "{{ mergerfs_root }}/Downloads/arm_completed:/home/arm/media/completed"
      - "{{ mergerfs_root }}/Downloads/arm_music:/home/arm/Music"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: unless-stopped

- name: Install the SWAG config files
  template:
    src: "{{ arm_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/internal/nginx/proxy-confs/{{ arm_container_name }}.subdomain.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
