---
- name: Create the necessary Firefox folder
  file:
    path: "{{ docker_dir }}/{{ firefox_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Make sure that Firefox container is created and running
  docker_container:
    name: "{{ firefox_container_name }}"
    image: lscr.io/linuxserver/mullvad-browser:latest
    pull: true
    capabilities:
      - net_admin
    security_opts:
      - seccomp:unconfined
    networks:
      - name: swag_network
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      TITLE: FirefoxVNC
      DRINODE: /dev/dri/renderD128
      DOCKER_MODS: linuxserver/mods:firefox-fonts
    shm_size: 2G
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - "{{ mergerfs_root }}/Downloads:/config/Downloads"
      - "{{ docker_dir }}/{{ firefox_container_name }}:/config/.mozilla/firefox"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ firefox_dashboard_name }}"

- name: Install the SWAG config files
  template:
    src: "{{ firefox_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ firefox_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
