---
- name: Create the necessary folder (1)
  file:
    path: "{{ docker_dir }}/{{ influxdb_container_name }}/config"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create the necessary folder (2)
  file:
    path: "{{ docker_dir }}/{{ influxdb_container_name }}/data"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that InfluxDB container is created and running
  community.docker.docker_container:
    name: "{{ influxdb_container_name }}"
    image: influxdb:2
    pull: true
    networks:
      - name: "{{ influxdb_network_name }}"
    state: started
    env:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: "{{ influxdb_user }}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "{{ influxdb_pass }}"
      DOCKER_INFLUXDB_INIT_ORG: "{{ influxdb_org }}"
      DOCKER_INFLUXDB_INIT_BUCKET: "{{ influxdb_bucket }}"
      DOCKER_INFLUXDB_INIT_RETENTION: 2ew
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ influxdb_token }}"
    volumes:
      - "{{ docker_dir }}/{{ influxdb_container_name }}/data:/var/lib/influxdb2"
      - "{{ docker_dir }}/{{ influxdb_container_name }}/config:/etc/influxdb2"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8086:8086/tcp
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ influxdb_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ influxdb_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "{{ influxdb_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ influxdb_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

# docker exec influxdb influx auth create --org "catafalco" --read-authorizations --write-authorizations --read-buckets --write-buckets --read-dashboards
#   --write-dashboards --read-tasks --write-tasks --read-telegrafs  --write-telegrafs --read-users --write-users --read-variables --write-variables
#   --read-secrets --write-secrets --read-labels --write-labels --read-views --write-views --read-documents --write-documents --read-notificationRules
#   --write-notificationRules --read-notificationEndpoints --write-notificationEndpoints --read-checks --write-checks --read-dbrp --write-dbrp
#   --read-annotations --write-annotations --read-sources --write-sources --read-scrapers --write-scrapers --read-notebooks --write-notebooks --read-remotes
#   --write-remotes --read-replications --write-replications

- name: Setup backup cron job
  ansible.builtin.include_tasks: tasks/backup_service.yml
  vars:
    service_name: "{{ influxdb_container_name }}"
    cron_schedule: "0 5 * * *"
    backup_cli_args:
      source_paths: "{{ docker_dir }}/{{ influxdb_container_name }}"
      destination_path: "{{ mergerfs_root }}/docker-volumes-backup"
      container_names_str: "{{ influxdb_container_name }}"
