---
- name: Create the config folder
  become: true
  file:
    path: "{{ docker_dir }}/{{ container_name }}/config"
    state: directory
    mode: "0755"
    owner: 1883
    group: 1883

- name: Copy mosquitto.conf
  become: true
  copy:
    src: files/mosquitto.conf
    dest: "{{ docker_dir }}/{{ container_name }}/config/mosquitto.conf"
    mode: "0644"
    owner: 1883
    group: 1883

- name: Create mosquitto.passwd
  become: true
  file:
    path: "{{ docker_dir }}/{{ container_name }}/config/mosquitto.passwd"
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: "0644"
    owner: 1883
    group: 1883

- name: Check if mosquitto.passwd is populated
  become: true
  lineinfile:
    path: "{{ docker_dir }}/{{ container_name }}/config/mosquitto.passwd"
    regexp: ^mosquitto.*$
    state: absent
  register: mosquitto_passwd_present
  changed_when: not mosquitto_passwd_present.changed
  check_mode: true
  notify:
    - Generate the password
