# See here for hardware capabilities https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video
# 1. Verify which pkg is required (intel-media or i965), see Arch Wiki: https://wiki.archlinux.org/title/Hardware_video_acceleration
# 2. Bind `/dev/dri/card0` and `/dev/dri/renderD128`
# 3. Add the hw render group. `cat /etc/group | grep render`
# 4. If relying on old i965, purge `intel-media-*` in the container via `docker exec`.
# Bonus. Enable GuC and HuC: https://gist.github.com/Brainiarc7/aa43570f512906e882ad6cdd835efe57
---
- name: Make sure that QuickSync packages are installed
  become: true
  package:
    name:
      - vainfo
      - intel-media-va-driver-non-free
      - intel-gpu-tools
    state: present

- name: Create the Jellyfin folder
  file:
    path: "{{ docker_dir }}/{{ jellyfin_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that Jellyfin container is created and running
  docker_container:
    name: "{{ jellyfin_container_name }}"
    image: ghcr.io/linuxserver/jellyfin:latest
    pull: true
    networks:
      - name: "{{ jellyfin_network_name }}"
    exposed_ports:
      - 8096
    privileged: true
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    state: started
    healthcheck:  # it doesn't work :-(
      "test": ["CMD", "curl", "--fail", "http://{{ jellyfin_container_name }}:8096/health"]
      retries: 3
      start_period: 30s
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      UMASK: "002"
      TZ: "{{ timezone }}"
      VERSION: latest
      JELLYFIN_PublishedServerUrl: "https://jellyfin.{{ site_url }}"
      DOCKER_MODS: linuxserver/mods:jellyfin-opencl-intel
    groups:
      - 109
    volumes:
      - "{{ docker_dir }}/{{ jellyfin_container_name }}:/config"
      - "{{ mergerfs_root }}/Media/Transcodes:/config/data/transcodes"
      - "{{ mergerfs_root }}/Media/Movies:/data/movies"
      - "{{ mergerfs_root }}/Media/TV:/data/tv"
      - "{{ mergerfs_root }}/Media/Books:/data/books:ro"
      - "{{ mergerfs_root }}/Media/Music:/data/music:ro"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ jellyfin_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ jellyfin_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "{{ jellyfin_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ jellyfin_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Enable Prometheus metrics
  ansible.builtin.lineinfile:
    path: "{{ docker_dir }}/{{ jellyfin_container_name }}/system.xml"
    search_string: "  <EnableMetrics>false</EnableMetrics>"
    line: "  <EnableMetrics>true</EnableMetrics>"
