---
- name: Set SSH correctly before executing other roles
  hosts: nilde
  gather_facts: false
  pre_tasks:
    - name: Set SSH correctly before executing other roles
      import_tasks: tasks/ssh.yml
      tags:
        - port

- name: Install Docker
  hosts: nilde
  become: true
  roles:
    - role: geerlingguy.ntp
      tags:
        - ntp
    - role: system
      tags:
        - system
    - role: docker
      tags:
        - docker

- name: Install services
  hosts: nilde
  become: true
  roles:
    - role: swag
      tags:
        - swag
        - containers

    - role: authelia
      tags:
        - authelia
        - containers

    - role: radicale
      tags:
        - radicale
        - containers

    - role: seafile
      tags:
        - seafile
        - containers

    - role: ntfy
      tags:
        - ntfy
        - containers

    - role: vaultwarden
      tags:
        - vaultwarden
        - containers

    - role: watchtower
      tags:
        - watchtower
        - containers
