---
- name: Set SSH correctly before executing other roles
  hosts: pihole-one
  become: true

  pre_tasks:
#    - name: Set SSH correctly before executing other roles
#      import_tasks: tasks/ssh.yml
#      tags:
#        - port

    - name: Configure timezone
      community.general.timezone:
        name: "{{ timezone | default('UTC') }}"

    - name: Get current status of time synchronization
      ansible.builtin.command: timedatectl show -P NTPSynchronized
      register: ntp_status
      changed_when: false

    - name: Install NTP/chrony
      when: ntp_status.stdout != "yes"
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: started
        enabled: true

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

  tasks:
    - name: Install Pi-hole
      ansible.builtin.shell:
        cmd: curl -sSL https://install.pi-hole.net | bash
