---
roles:
  - name: geerlingguy.security
  - name: geerlingguy.ntp
  - name: chriswayg.msmtp-mailer
  - name: stuvusit.smartd
  - name: oefenweb.dns
  - name: notthebee.ubuntu_autoinstall
  - name: IronicBadger.snapraid
  - name: linux-system-roles.cockpit
  - name: stefangweichinger.ansible_rclone
  - name: simoncaron.nut

collections:
  - name: community.general
  - name: vladgh.samba
