---
#
# Tasks and roles for all hosts

#- hosts: catafalco
#  gather_facts: no
#
#  pre_tasks:
#    - import_tasks: tasks/ssh_juggle_port.yml
#      tags:
#        - port

- hosts: catafalco
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh.yml
      tags:
        - port

- hosts: catafalco
  become: yes
  roles:

    #
    # Basics
    #
    - role: system
      tags: 
        - system

    - role: chriswayg.msmtp-mailer
      tags: 
        - msmtp

    - role: oefenweb.dns
      tags:
        - dns

    - role: geerlingguy.ntp
      tags: 
        - ntp

    #
    # Security
    #
    - role: security/fail2ban
      tags:
        - fail2ban

    - role: security/endlessh
      tags:
        - endlessh
      when: enable_endlessh | default(False)

    - role: geerlingguy.security
      tags: 
        - security

    - role: linux-system-roles.cockpit
      tags:
        - cockpit
      when: enable_cockpit | default(False)

    #
    # Filesystems
    #
    - role: filesystems/mergerfs
      become: yes
      tags:
        - mergerfs
      when: enable_nas_stuff | default(False)

    - role: filesystems/mounts
      become: yes
      tags:
        - mounts
      when: enable_nas_stuff | default(False)

    - role: filesystems/hd-idle
      become: yes
      tags:
        - hd-idle
      when: enable_nas_stuff | default(False)

    - role: stuvusit.smartd
      become: yes
      tags:
        - smartd
      when: enable_nas_stuff | default(False)

    - role: ironicbadger.ansible_role_snapraid
      become: yes
      tags:
        - snapraid
      when: enable_nas_stuff | default(False)


    #
    # Docker
    #
    - role: docker
      tags:
        - docker

    ########################################
    ############## Containers ##############
    ########################################
    #
    # Network
    #
    - role: network/swag
      become: no
      tags: 
        - swag
        - containers
      when: enable_swag | default(False)

    - role: network/bunkerized-nginx
      become: no
      tags: 
        - bunkerized-nginx
        - containers
      when: enable_bunkerized_nginx | default(False)

    - role: network/wireguard
      become: no
      tags: 
        - wireguard
        - containers
      when: enable_wireguard | default(False)

    - role: network/ikev2
      become: no
      tags: 
        - ikev2
        - containers
      when: enable_ikev2 | default(False)

    - role: network/ddclient
      become: yes
      when: enable_ddclient | default(False)
      tags:
        - ddclient

    - role: network/duckdns
      become: no
      when: enable_duckdns | default(False)
      tags:
        - duckdns 

    - role: network/cloudflare-ddns
      become: no
      tags: 
        - cloudflare-ddns
        - containers
      when: enable_cloudflare | default(False)

    - role: network/pihole
      become: no
      when: enable_pihole | default(False)
      tags:
        - pihole 
        - containers

    - role: network/ikev2
      become: no
      when: enable_ikev2 | default(False)
      tags:
        - containers
        - ikev2 

    #
    # Homer
    #
    - role: homer
      become: no
      tags:
        - homer
        - containers
      when: enable_homer | default(False)

    #
    # System containers
    #
    - role: containers/system/authelia
      become: no
      tags:
        - authelia
        - containers
      when: enable_authelia | default(False)

    - role: containers/system/watchtower
      become: no
      tags:
        - watchtower
        - containers

    - role: containers/system/healthchecks
      become: no
      tags:
        - healthchecks
        - containers

    - role: containers/system/openspeedtest
      become: no
      tags:
        - openspeedtest
        - containers
      when: enable_openspeedtest | default(False)

    #
    # Monitoring
    #
    - role: containers/system/influxdb
      tags:
        - influxdb
        - containers
        - monitoring
      when: enable_influxdb | default(False)

    - role: monitoring/telegraf
      tags:
        - telegraf
        - monitoring
      when: enable_telegraf | default(False)

    - role: monitoring/ups
      tags:
        - ups
        - nut
        - monitoring
      when: enable_ups | default(False)

    #
    # ServArr
    #
    - role: containers/servarr/deluge
      become: no
      tags:
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: containers/servarr/sonarr
      become: no
      tags:
        - sonarr
        - containers
      when: enable_sonarr | default(False)

    - role: containers/servarr/radarr
      become: no
      tags:
        - radarr
        - containers
      when: enable_radarr | default(False)

    - role: containers/servarr/lidarr
      become: no
      tags:
        - lidarr
        - containers
      when: enable_lidarr | default(False)

    - role: containers/servarr/prowlarr
      become: no
      tags:
        - prowlarr
        - containers
      when: enable_prowlarr | default(False)

    #
    # Media
    #
    - role: containers/media/jellyfin
      become: no
      tags:
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/media/paperless
      become: no
      tags:
        - paperless
        - containers
      when: enable_paperless | default(False)

    - role: containers/media/photoprism
      become: no
      tags:
        - photoprism
        - containers
      when: enable_photoprism | default(False)

    - role: containers/media/koel
      become: no
      tags:
        - koel
        - containers
      when: enable_koel | default(False)

    - role: containers/media/navidrome
      become: no
      tags:
        - navidrome
        - containers
      when: enable_navidrome | default(False)

    - role: containers/media/beets
      become: no
      tags:
        - beets
        - containers
      when: enable_beets | default(False)

    - role: containers/media/openbooks
      become: no
      tags:
        - openbooks
        - containers
      when: enable_openbooks | default(False)

    #
    # Personal
    #
    - role: containers/personal/firefly
      become: no
      tags:
        - firefly
        - containers
      when: enable_firefly | default(False)

    #
    # Services
    #
    - role: containers/services/nextcloud
      become: no
      tags:
        - nextcloud
        - containers
      when: enable_nextcloud | default(False)

    - role: containers/services/duplicati
      become: no
      tags:
        - duplicati
        - backup-sync
        - containers
      when: enable_duplicati | default(False)

    - role: containers/services/syncthing
      become: no
      tags:
        - syncthing
        - containers
      when: enable_syncthing | default(False)

    - role: backup-sync/rclone
      tags:
        - rclone
        - backup-sync
      when: enable_rclone | default(False)

    - role: containers/services/vaultwarden
      become: no
      tags:
        - vaultwarden
        - containers
      when: enable_vaultwarden | default(False)

    #
    # Samba
    #
    - role: bertvv.samba
      become: yes
      tags:
        - samba
      when: enable_nas_stuff | default(False)
