---
# Tasks and roles for all hosts

# - hosts: catafalco
#   gather_facts: no
#   pre_tasks:
#     - import_tasks: tasks/ssh_juggle_port.yml
#       tags:
#         - port

- name: Set SSH correctly before executing other roles
  hosts: catafalco
  gather_facts: false
  pre_tasks:
    - name: Set SSH correctly before executing other roles
      import_tasks: tasks/ssh.yml
      tags:
        - port

- name: Full list of roles
  hosts: catafalco
  become: true
  roles:
    #
    # Basics
    #
    - role: system
      tags:
        - system

    - role: chriswayg.msmtp-mailer
      tags:
        - msmtp

    - role: oefenweb.dns
      tags:
        - dns

    - role: geerlingguy.ntp
      tags:
        - ntp

    #
    # Security
    #
    - role: geerlingguy.security
      tags:
        - security

    - role: linux-system-roles.cockpit
      tags:
        - cockpit
      when: enable_cockpit | default(False)

    #
    # Filesystems
    #
    - role: mergerfs
      become: true
      tags:
        - mergerfs
      when: enable_nas_stuff | default(False)

    - role: mounts
      become: true
      tags:
        - mounts
      when: enable_nas_stuff | default(False)

    - role: hd-idle
      become: true
      tags:
        - hd-idle
      when: enable_nas_stuff | default(False)

    - role: stuvusit.smartd
      become: true
      tags:
        - smartd
      when: enable_nas_stuff | default(False)

    - role: IronicBadger.snapraid
      become: true
      tags:
        - snapraid
      when: enable_nas_stuff | default(False)

    #
    # Docker
    #
    - role: docker
      tags:
        - docker

    ########################################
    ############## Containers ##############
    ########################################
    #
    # Network
    #
    - role: swag
      become: false
      tags:
        - swag
        - containers
      when: enable_swag | default(False)

    #
    # Homer
    #
    - role: homer
      become: false
      tags:
        - homer
        - containers
      when: enable_homer | default(False)

    #
    # System containers
    #
    - role: watchtower
      become: false
      tags:
        - watchtower
        - containers

    - role: healthchecks
      become: false
      tags:
        - healthchecks
        - containers

    #
    # Monitoring
    #
    - role: influxdb
      tags:
        - influxdb
        - containers
        - monitoring
      when: enable_influxdb | default(False)

    - role: telegraf
      tags:
        - telegraf
        - monitoring
      when: enable_telegraf | default(False)

    - role: nut
      tags:
        - ups
        - nut
        - monitoring
      when: enable_nut | default(False)

    #
    # ServArr
    #
    - role: deluge
      become: false
      tags:
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: sonarr
      become: false
      tags:
        - sonarr
        - containers
      when: enable_sonarr | default(False)

    - role: radarr
      become: false
      tags:
        - radarr
        - containers
      when: enable_radarr | default(False)

    - role: lidarr
      become: false
      tags:
        - lidarr
        - containers
      when: enable_lidarr | default(False)

    - role: readarr
      become: false
      tags:
        - readarr
        - containers
      when: enable_readarr | default(False)

    - role: prowlarr
      become: false
      tags:
        - prowlarr
        - containers
      when: enable_prowlarr | default(False)

    #
    # Media
    #
    - role: jellyfin
      become: false
      tags:
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: photoprism
      become: false
      tags:
        - photoprism
        - containers
      when: enable_photoprism | default(False)

    - role: navidrome
      become: false
      tags:
        - navidrome
        - containers
      when: enable_navidrome | default(False)

    - role: calibreweb
      become: false
      tags:
        - calibreweb
        - containers
      when: enable_calibreweb | default(False)

    - role: arm
      become: false
      tags:
        - arm
        - containers
      when: enable_arm | default(False)

    - role: handbrake
      become: false
      tags:
        - handbrake
        - containers
      when: enable_handbrake | default(False)

    #
    # Services
    #
    - role: duplicati
      become: false
      tags:
        - duplicati
        - backup-sync
        - containers
      when: enable_duplicati | default(False)

    - role: firefox
      become: false
      tags:
        - firefox
        - containers
      when: enable_firefox | default(False)

    - role: invidious
      become: false
      tags:
        - invidious
        - containers
      when: enable_invidious | default(False)

    - role: speedtest_tracker
      become: false
      tags:
        - speedtest
        - containers
      when: enable_speedtest_tracker | default(False)

    - role: rclone
      tags:
        - rclone
        - backup-sync
      when: enable_rclone | default(False)

    #
    # Samba
    #
    - role: vladgh.samba.server
      become: true
      tags:
        - samba
      when: enable_nas_stuff | default(False)
