---
# Tasks and roles for all hosts

- name: Set SSH correctly before executing other roles
  hosts: catafalco
  gather_facts: false
  pre_tasks:
#    - name: Juggle with SSH with default and custom port
#      import_tasks: tasks/ssh_juggle_port.yml
#      tags:
#        - port

    - name: Set SSH correctly before executing other roles
      import_tasks: tasks/ssh.yml
      tags:
        - port

- name: Full list of roles
  hosts: catafalco
  become: true
  roles:
    #
    # Basics
    #
    - role: system
      tags:
        - system

    - role: chriswayg.msmtp-mailer
      tags:
        - msmtp

    - role: oefenweb.dns
      tags:
        - dns

    - role: geerlingguy.ntp
      tags:
        - ntp

    #
    # Security
    #
    - role: geerlingguy.security
      tags:
        - security

    #
    # Filesystems
    #
    - role: mergerfs
      become: true
      tags:
        - mergerfs
      when: enable_nas_stuff | default(False)

    - role: mounts
      become: true
      tags:
        - mounts
      when: enable_nas_stuff | default(False)

    - role: hd_idle
      become: true
      tags:
        - hd-idle
      when: enable_nas_stuff | default(False)

    - role: stuvusit.smartd
      become: true
      tags:
        - smartd
      when: enable_nas_stuff | default(False)

    - role: snapraid
      become: true
      tags:
        - snapraid
      when: enable_nas_stuff | default(False)

    #
    # Samba
    #
    - role: vladgh.samba.server
      become: true
      tags:
        - samba
      when: enable_nas_stuff | default(False)

    #
    # Docker
    #
    - role: docker
      tags:
        - docker

    ########################################
    ############## Containers ##############
    ########################################
    #
    # Network
    #
    - role: swag
      become: false
      tags:
        - swag
        - containers

    #
    # Homer
    #
    - role: homer
      become: false
      tags:
        - homer
        - containers

    #
    # System containers
    #
    - role: watchtower
      become: false
      tags:
        - watchtower
        - containers

    - role: healthchecks
      become: false
      tags:
        - healthchecks
        - containers

    - role: socket_proxy
      become: false
      tags:
        - socket-proxy
        - containers

    - role: wud
      become: false
      tags:
        - wud
        - containers

    #
    # Monitoring
    #
    - role: influxdb
      tags:
        - influxdb
        - containers
        - monitoring

    - role: telegraf
      tags:
        - telegraf
        - monitoring

    - role: nut
      tags:
        - ups
        - nut
        - monitoring

    - role: uptime_kuma
      tags:
        - uptime_kuma
        - monitoring
        - containers

    #
    # ServArr
    #
    - role: deluge
      become: false
      tags:
        - deluge
        - servarr
        - containers

    - role: sonarr
      become: false
      tags:
        - sonarr
        - servarr
        - containers

    - role: radarr
      become: false
      tags:
        - radarr
        - servarr
        - containers

    - role: lidarr
      become: false
      tags:
        - lidarr
        - servarr
        - containers

    - role: readarr
      become: false
      tags:
        - readarr
        - servarr
        - containers

    - role: prowlarr
      become: false
      tags:
        - prowlarr
        - servarr
        - containers

    - role: slskd
      become: false
      tags:
        - slskd
        - servarr
        - containers

    #
    # Media
    #
    - role: jellyfin
      become: false
      tags:
        - jellyfin
        - containers

    - role: immich
      become: false
      tags:
        - immich
        - containers

    - role: navidrome
      become: false
      tags:
        - navidrome
        - containers

    - role: calibreweb
      become: false
      tags:
        - calibreweb
        - containers

    - role: arm
      become: false
      tags:
        - arm
        - containers

    - role: handbrake
      become: false
      tags:
        - handbrake
        - containers

    - role: stirling_pdf
      become: false
      tags:
        - pdf
        - containers

    #
    # Services
    #
    - role: actual_budget
      become: false
      tags:
        - actual
        - containers

    - role: duplicati
      become: false
      tags:
        - duplicati
        - backup-sync
        - containers

    - role: firefox
      become: false
      tags:
        - firefox
        - containers

    - role: invidious
      become: false
      tags:
        - invidious
        - containers

    - role: speedtest_tracker
      become: false
      tags:
        - speedtest
        - containers

    - role: rclone
      tags:
        - rclone
        - backup-sync

    - role: vaultwarden
      tags:
        - vaultwarden
        - containers

    - role: dawarich
      tags:
        - dawarich
        - containers

    - role: seafile
      tags:
        - seafile
        - containers

    - role: radicale
      tags:
        - radicale
        - calendar
        - containers
