---
- name: Create a docker network
  community.docker.docker_network:
    name: "{{ wud_network_name }}"
    connected:
      - "{{ item }}"
    appends: true
  loop:
    - "{{ swag_container_name }}"
    - "{{ socket_proxy_container_name }}"
