---
- name: Create the necessary {{ container_name }} folder
  file:
    path: "{{ docker_dir }}/{{ container_name }}/config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Install {{ container_name }} configuration template
  template:
    src: config.yaml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/config/config.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
  register: configuration

- name: Make sure that Beets container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: lscr.io/linuxserver/beets:latest
    pull: yes
    networks:
      - name: swag_internal_network
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ mergerfs_root }}:/storage"
    restart_policy: unless-stopped