---
jellyfin_container_name: jellyfin
jellyfin_dashboard_url: https://jellyfin.{{ host_local }}
jellyfin_dashboard_name: Jellyfin
jellyfin_homer_category: media
jellyfin_health_url: http://{{ ansible_default_ipv4.address }}:3000/http://jellyfin:8096
