---
- name: Create the necessary Stirling PDF folders
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ stirling_pdf_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Make sure that Stirling PDF container is created and running
  docker_container:
    name: "{{ stirling_pdf_container_name }}"
    image: frooodle/s-pdf:latest-ultra-lite
    pull: true
    networks:
      - name: swag_network
    state: started
    env:
      DOCKER_ENABLE_SECURITY: "true"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
      LANGS: en_GB
    volumes:
      - "{{ docker_dir }}/{{ stirling_pdf_container_name }}/extraConfigs:/configs"
      - "{{ docker_dir }}/{{ stirling_pdf_container_name }}/trainingData:/usr/share/tessdata"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ stirling_pdf_dashboard_name }}"

- name: Install the SWAG config files
  template:
    src: "templates/{{ stirling_pdf_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ stirling_pdf_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
