#
# Gets variables from all web applications recursively (for Homer and SWAG)
#
---
- name: Include all default.yml files
  include_vars:
    dir: "{{ playbook_dir }}/roles/{{ item }}/defaults"
    files_matching: main.yml
    name: "{{ item }}"
  loop: "{{ containers }}"

- name: Populate the dictionary of all containers
  set_fact:
    web_applications: >
      "{{ web_applications | default([]) + [{'logo': '/assets/tools/homer-icons/' + item + '.png', 'name': lookup('vars', item)[item + '_dashboard_name']
      | default(item | title), 'url': lookup('vars', item)[item + '_dashboard_url'] | default(''), 'endpoint': lookup('vars', item)[item + '_health_url'] |
      default(''), 'category': lookup('vars', item)[item + '_homer_category'] | default('')}] }}"
  loop: "{{ containers }}"

- name: Populate the URL dictionary with all containers
  set_fact:
    swag_urls: "{{ swag_urls | default({}) | combine({item: lookup('vars', item)['dashboard_url'] | default('') | regex_replace('https?://|/*', '')}) }}"
  loop: "{{ containers }}"
