#
# Gets variables from all web applications recursively (for Homer and SWAG)
#
---
- name: Include all default.yml files
  include_vars:
    dir: "{{ playbook_dir }}/roles/{{ item }}/defaults"
    files_matching: main.yml
    name: "{{ item }}"
  loop: "{{ containers }}"

# Create a variable 'web_applications' as a list of all containers which have a variable 'name_dashboard_url' defined.
# Each element is a dictionary of the kind:
#  {
#     name: jellyfin
#     logo: '/assets/tools/homer-icons/jellyfin.png'
#     dashboard: Jellyfin
#     url: jellyfin.catafal.co
#     health_url: ''  # not used anywhere yet
#     category: Media
#  }
- name: Populate the dictionary of all containers
  set_fact:
    dashboard_apps: "{{ dashboard_apps | default([]) + [{'name': item, 'logo': '/assets/tools/homer-icons/' + item + '.png', 'url': lookup('vars', item)[item +
    '_dashboard_url'] | default(''), 'target': '_blank', 'type': 'Ping', 'method': 'get'} | ansible.builtin.combine(lookup('vars', item)[item + '_homer'] |
    default({}))] }}"
  when: lookup('vars', item)[item + '_dashboard_url'] is defined
  loop: "{{ containers }}"
