---
# To split CUE files you can run the following command:
# $ shnsplit -f file.cue -o flac file.flac
# or possibly:
# for album in *.flac; do shnsplit -f "${album%.flac}".cue -o flac -t "%n - %t" "$album"; done

- name: Make sure that `shntool` and `cuetools` packages are installed
  become: true
  ansible.builtin.package:
    name:
      - shntool
      - flac
      - cuetools
    state: present

- name: Create the necessary Lidarr folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ lidarr_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Copy the ReplayGain script
  ansible.builtin.copy:
    src: replaygain.sh
    dest: "{{ docker_dir }}/{{ lidarr_container_name }}/replaygain.sh"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that Lidarr container is created and running
  docker_container:
    name: "{{ lidarr_container_name }}"
    image: ghcr.io/linuxserver/lidarr
    pull: true
    networks:
      - name: "{{ lidarr_network_name }}"
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      DOCKER_MODS: "linuxserver/mods:universal-package-install"
      INSTALL_PACKAGES: "rsgain"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_dir }}/{{ lidarr_container_name }}:/config"
      - "{{ mergerfs_root }}:/storage"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ lidarr_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ lidarr_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "{{ lidarr_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ lidarr_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
