---
- name: Create the Actual Budget folder
  file:
    path: "{{ docker_dir }}/{{ actual_budget_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that Actual Budget container is created and running
  community.docker.docker_container:
    name: "{{ actual_budget_container_name }}"
    image: actualbudget/actual-server:latest
    pull: true
    networks:
      - name: "{{ actual_budget_network_name }}"
    exposed_ports:
      - 5006
    state: started
    user: "{{ guid }}:{{ guid }}"
    volumes:
      - "{{ docker_dir }}/{{ actual_budget_container_name }}:/data"
    restart_policy: unless-stopped
    healthcheck:
      "test": ["CMD-SHELL", "node src/scripts/health-check.js"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ actual_budget_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ actual_budget_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "templates/{{ actual_budget_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ actual_budget_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
