---
- name: Mount the data drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  with_items: "{{ disks }}"
  when: disks[0] is defined

- name: Mount the cache drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    state: mounted
    opts: defaults,discard
    passno: "2"
  with_items: "{{ cache_disks }}"
  when: cache_disks[0] is defined

- name: Mount the parity drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: mounted
    passno: "2"
  with_items: "{{ parity_disks }}"
  when: parity_disks[0] is defined

- name: Mount the mergerfs cached array
  mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/cache*:/mnt/data*
    opts: defaults,category.create=lfs,dropcacheonclose=1,allow_other,use_ino,moveonenospc=1,minfreespace=50G,fsname=mergerfs
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined

- name: Mount the mergerfs array
  mount:
    name: "{{ mergerfs_root }}_slow"
    src: /mnt/data*
    opts: defaults,category.create=mfs,dropcacheonclose=1,allow_other,use_ino,moveonenospc=1,minfreespace=500G,fsname=mergerfs_slow
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined

- name: Mount the mergerfs cache-only array
  mount:
    name: "{{ cache_root }}"
    src: /mnt/cache*
    opts: defaults,category.create=mfs,dropcacheonclose=1,allow_other,use_ino,fsname=mergerfs_cache
    fstype: fuse.mergerfs
    state: mounted
  when: cache_disks[0] is defined

# - name: Mount the Time Machine drive
#   mount:
#     name: "{{ timemachine_root }}"
#     src: "{{ timemachine_drive }}"
#     fstype: ext4
#     opts: defaults,discard
#     state: mounted
#     passno: "2"
#   when: enable_timemachine | default(False)
