---
nut_managed_config: true
nut_host: "0.0.0.0"
nut_user: monitor
nut_password: "{{ nut_monitor_password }}"
nut_mode: netserver
nut_services:
  - nut-monitor
  - nut-server
  - nut-driver@epyc-ion
nut_ups:
  - name: epyc-ion
    driver: usbhid-ups
    device: auto
    description: Epyc ION UPS
nut_upsd_extra: LISTEN 0.0.0.0 3493
