---
nut_managed_config: true
nut_host: "0.0.0.0"
nut_user: monitor
nut_password: "{{ nut_monitor_password }}"
nut_mode: netserver
nut_services:
  - nut-monitor
  - nut-server
  - nut-driver@powerwalker
nut_ups:
  - name: powerwalker
    driver: usbhid-ups
    device: auto
    description: PowerWalker VI 500 R1U
nut_upsd_extra: LISTEN 0.0.0.0 3493
