---
- name: Create the necessary Navidrome folder
  file:
    path: "{{ docker_dir }}/{{ container_name }}/data"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Make sure that Navidrome container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: deluan/navidrome:latest
    pull: true
    networks:
      - name: swag_internal_network
    state: started
    user: "{{ guid }}:{{ guid }}"
    env:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_DEFAULTTHEME: Spotify-ish
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
      - "{{ mergerfs_root }}/Media/Music:/music:ro"
    restart_policy: unless-stopped
