---
- name: Create the necessary Navidrome folder
  file:
    path: "{{ docker_dir }}/{{ navidrome_container_name }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - data
    - backup

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that Navidrome container is created and running
  community.docker.docker_container:
    name: "{{ navidrome_container_name }}"
    image: deluan/navidrome:latest
    pull: true
    networks:
      - name: "{{ navidrome_network_name }}"
    state: started
    user: "{{ guid }}:{{ guid }}"
    env:
      ND_DEFAULTTHEME: Nord
      ND_SCANNER_PURGEMISSING: always
      ND_SCANSCHEDULE: 1h
      ND_SESSIONTIMEOUT: 24h
      ND_LOGLEVEL: info
      ND_HTTPSECURITYHEADERS_CUSTOMFRAMEOPTIONSVALUE: SAMEORIGIN
      ND_BACKUP_PATH: /backup
      ND_BACKUP_SCHEDULE: "0 0 * * 0"
      ND_BACKUP_COUNT: "4"
    volumes:
      - "{{ docker_dir }}/{{ navidrome_container_name }}/data:/data"
      - "{{ docker_dir }}/{{ navidrome_container_name }}/backup:/backup"
      - "{{ mergerfs_root }}/Media/Music:/music:ro"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ navidrome_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ navidrome_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "templates/{{ navidrome_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ navidrome_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Setup backup cron job
  ansible.builtin.include_tasks: tasks/backup_service.yml
  vars:
    service_name: "{{ navidrome_container_name }}"
    cron_schedule: "0 5 * * *"
    backup_cli_args:
      source_paths: "{{ docker_dir }}/{{ navidrome_container_name }}"
      destination_path: "{{ mergerfs_root }}/docker-volumes-backup"
      container_names_str: "{{ navidrome_container_name }}"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: replaygain_check.yml
