---
- name: Create the necessary Navidrome folder
  file:
    path: "{{ docker_dir }}/{{ navidrome_container_name }}/data"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Make sure that Navidrome container is created and running
  docker_container:
    name: "{{ navidrome_container_name }}"
    image: deluan/navidrome:latest
    pull: true
    networks:
      - name: swag_network
    state: started
    user: "{{ guid }}:{{ guid }}"
    env:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_DEFAULTTHEME: Nord
      ND_HTTPSECURITYHEADERS_CUSTOMFRAMEOPTIONSVALUE: SAMEORIGIN
    volumes:
      - "{{ docker_dir }}/{{ navidrome_container_name }}/data:/data"
      - "{{ mergerfs_root }}/Media/Music:/music:ro"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ navidrome_dashboard_name }}"

- name: Install the SWAG config files
  template:
    src: "templates/{{ navidrome_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ navidrome_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
