---
- name: Make sure that Unifi container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: ghcr.io/linuxserver/unifi-controller
    networks:
      - name: swag_internal_macvlan
        ipv4_address: "{{ ip_address }}"
    pull: true
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
    restart_policy: unless-stopped
