---
- name: Create the necessary Readarr folder
  file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Make sure that Readarr container is created and running
  docker_container:
    name: "{{ readarr_container_name }}"
    image: lscr.io/linuxserver/readarr:develop
    pull: true
    networks:
      - name: swag_internal_network
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}:/storage"
    restart_policy: unless-stopped
