---
- name: Create the necessary Readarr folder
  file:
    path: "{{ docker_dir }}/{{ readarr_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that Readarr container is created and running
  docker_container:
    name: "{{ readarr_container_name }}"
    image: lscr.io/linuxserver/readarr:develop
    pull: true
    networks:
      - name: "{{ readarr_network_name }}"
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_dir }}/{{ readarr_container_name }}:/config"
      - "{{ mergerfs_root }}:/storage"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ readarr_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ readarr_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "{{ readarr_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ readarr_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
