---
- name: Create the necessary HandBrake folder
  file:
    path: "{{ docker_dir }}/{{ handbrake_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Make sure that HandBrake container is created and running
  community.docker.docker_container:
    name: "{{ handbrake_container_name }}"
    image: jlesage/handbrake:latest
    pull: true
    networks:
      - name: "{{ handbrake_network_name }}"
    state: started
    env:
      USER_ID: "{{ guid }}"
      GROUP_ID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_dir }}/{{ handbrake_container_name }}:/config"
      - "{{ mergerfs_root }}/Downloads:/storage:ro"
      - "{{ mergerfs_root }}/Downloads/hb_watch:/watch"
      - "{{ mergerfs_root }}/Downloads/hb_completed:/output"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ handbrake_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ handbrake_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "{{ handbrake_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ handbrake_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Setup backup cron job
  ansible.builtin.include_tasks: tasks/backup_service.yml
  vars:
    service_name: "{{ handbrake_container_name }}"
    cron_schedule: "0 5 4 * *"
    backup_cli_args:
      source_paths: "{{ docker_dir }}/{{ handbrake_container_name }}"
      destination_path: "{{ mergerfs_root }}/docker-volumes-backup"
      container_names_str: "{{ handbrake_container_name }}"
