---
- name: Create the necessary HandBrake folder
  file:
    path: "{{ docker_dir }}/{{ handbrake_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Make sure that HandBrake container is created and running
  docker_container:
    name: "{{ handbrake_container_name }}"
    image: jlesage/handbrake:latest
    pull: true
    networks:
      - name: swag_network
    state: started
    env:
      USER_ID: "{{ guid }}"
      GROUP_ID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ docker_dir }}/{{ handbrake_container_name }}:/config"
      - "{{ mergerfs_root }}/Downloads:/storage:ro"
      - "{{ mergerfs_root }}/Downloads/hb_watch:/watch"
      - "{{ mergerfs_root }}/Downloads/hb_completed:/output"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ handbrake_dashboard_name }}"

- name: Install the SWAG config files
  template:
    src: "{{ handbrake_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ handbrake_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
