---
- name: Install fail2ban filter configuration
  ansible.builtin.copy:
    src: fail2ban_filter.conf
    dest: "{{ swag_volume_fail2ban }}/filter.d/nextcloud.local"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: '0644'

- name: Install fail2ban jail configuration
  ansible.builtin.blockinfile:
    path: "{{ swag_volume_fail2ban }}/jail.local"
    marker: "# {mark} ANSIBLE | NEXTCLOUD CONFIGURATION"
    prepend_newline: true
    block: |
      [nextcloud]
      backend = auto
      enabled = true
      port = 80,443
      protocol = tcp
      filter = nextcloud
      action = {{ 'cloudflare-token' if swag_cloudflare_tunnel_enable | default(False) else 'iptables-allports' }}[name=nextcloud,cftoken="{{
        cloudflare_api_token }}"]
      logpath = {{ swag_fail2ban_monitored_logs }}/nextcloud.log

- name: Add Nextcloud to the list of logs to be mounted by SWAG
  ansible.builtin.set_fact:
    swag_container_volumes: "{{ swag_container_volumes + [nextcloud_log_file + ':' + swag_fail2ban_monitored_logs + '/nextcloud.log:ro'] }}"
