---
- name: Create the necessary SWAG folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0750"
  loop:
    - "{{ swag_volume_nginx }}"
    - "{{ swag_volume_fail2ban }}"

- name: Install the SWAG dashboard config file
  ansible.builtin.template:
    src: nginx/proxy-confs/dashboard.subdomain.conf.j2
    dest: "{{ swag_volume_nginx_proxy_confs }}/dashboard.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Create a docker network
  community.docker.docker_network:
    name: "{{ swag_network_name }}"
    connected:
      - "{{ swag_container_name }}"
    appends: true

- name: Add optional 'Cloudflare tunnel' Docker mod and ENV vars
  when: swag_cloudflare_tunnel_enable | default(False)
  block:
    - name: Append Docker mod
      ansible.builtin.set_fact:
        swag_container_env_vars: "{{ swag_container_env_vars |
        ansible.builtin.combine({'DOCKER_MODS': swag_container_env_vars.DOCKER_MODS +
        '|linuxserver/mods:universal-cloudflared|linuxserver/mods:swag-cloudflare-real-ip'}) }}"
    - name: Add ENV vars
      ansible.builtin.set_fact:
        swag_container_env_vars: "{{ swag_container_env_vars | ansible.builtin.combine({item[0]: item[1]}) }}"
      loop:
        - ["CF_ZONE_ID", "{{ cloudflare_zone_id[site_url] }}"]
        - ["CF_ACCOUNT_ID", "{{ cloudflare_account_id }}"]
        - ["CF_API_TOKEN", "{{ cloudflare_api_token }}"]
        - ["CF_TUNNEL_NAME", "{{ site_url }}"]
        - ["CF_TUNNEL_PASSWORD", "{{ cloudflare_tunnel_password }}"]
        - ["FILE__CF_TUNNEL_CONFIG", "/config/tunnelconfig.yml"]
    - name: Copy the configuration for the tunnel
      ansible.builtin.template:
        src: tunnelconfig.yml.j2
        dest: "{{ docker_dir }}/{{ swag_container_name }}/tunnelconfig.yml"
        owner: "{{ guid }}"
        group: "{{ guid }}"
        mode: "0644"
    - name: Strip container published ports
      ansible.builtin.set_fact:
        swag_container_ports: []
    - name: Update `nginx.conf` configuration for real ip
      ansible.builtin.lineinfile:
        path: "{{ docker_dir }}/{{ swag_container_name }}/nginx/nginx.conf"
        search_string: "{{ item[0] }}"
        insertafter: "http {"
        line: "{{ item[1] }}"
      loop:
        - ["set_real_ip_from 127.0.0.1;", "    set_real_ip_from 127.0.0.1;"]
        - ["include /config/nginx/cf_real-ip.conf;", "    include /config/nginx/cf_real-ip.conf;"]
        - ["real_ip_recursive on;", "    real_ip_recursive on;"]
        - ["real_ip_header X-Forwarded-For;", "    real_ip_header X-Forwarded-For;"]
    - name: Add the volume for `tunnelconfig.yml`
      ansible.builtin.set_fact:
        swag_container_volumes: "{{ swag_container_volumes + [docker_dir + '/' + swag_container_name + '/tunnelconfig.yml:/config/tunnelconfig.yml'] }}"

# docker exec swag python3 /app/auto-uptime-kuma.py
- name: Add optional 'Auto Uptime Kuma' Docker mod and ENV vars
  when: "'uptime_kuma' in containers"
  block:
    - name: Run the Docker Socket Proxy
      ansible.builtin.include_role:
        name: socket_proxy
    - name: Create a docker network with 'socket-proxy' container
      community.docker.docker_network:
        name: "{{ swag_network_name }}"
        connected:
          - "{{ socket_proxy_container_name }}"
        appends: true
    - name: Append Docker mod
      ansible.builtin.set_fact:
        swag_container_env_vars: "{{ swag_container_env_vars | ansible.builtin.combine({'DOCKER_MODS': swag_container_env_vars.DOCKER_MODS +
        '|linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-uptime-kuma'}) }}"
    - name: Add ENV vars
      ansible.builtin.set_fact:
        swag_container_env_vars: "{{ swag_container_env_vars | ansible.builtin.combine({item[0]: item[1]}) }}"
      loop:
        - ["DOCKER_HOST", "{{ socket_proxy_container_name }}:2375"]
        - ["UPTIME_KUMA_URL", "http://{{ uptime_kuma_container_name }}:3001"]
        - ["UPTIME_KUMA_USERNAME", "{{ uptime_kuma_user }}"]
        - ["UPTIME_KUMA_PASSWORD", "{{ uptime_kuma_password }}"]

- name: Add optional 'Maxmind' Docker mod and ENV vars
  when: swag_maxmind_enable | default(False)
  block:
    - name: Append Docker mod
      ansible.builtin.set_fact:
        swag_container_env_vars: "{{ swag_container_env_vars |
        ansible.builtin.combine({'DOCKER_MODS': swag_container_env_vars.DOCKER_MODS + '|linuxserver/mods:swag-maxmind'}) }}"
    - name: Add ENV vars
      ansible.builtin.set_fact:
        swag_container_env_vars: "{{ swag_container_env_vars | ansible.builtin.combine({item[0]: item[1]}) }}"
      loop:
        - ["MAXMINDDB_LICENSE_KEY", "{{ maxmind_licence_key }}"]
        - ["MAXMINDDB_USER_ID", "{{ maxmind_account_id }}"]

#  This container includes fail2ban set up with 5 jails by default:
#    * nginx-http-auth
#    * nginx-badbots
#    * nginx-botsearch
#    * nginx-deny
#    * nginx-unauthorized
#  To enable or disable other jails, modify the file `/config/fail2ban/jail.local`
#  To modify filters and actions, instead of editing the .conf files, create .local files with the same name
#  and edit those because .conf files get overwritten when the actions and filters are updated. .local files
#  will append whatever's in the .conf files (ie. nginx-http-auth.conf --> nginx-http-auth.local).
#  You can check which jails are active via `docker exec -it swag fail2ban-client status`
#  You can check the status of a specific jail via `docker exec -it swag fail2ban-client status <jail name>`
#  You can unban an IP via `docker exec -it swag fail2ban-client set <jail name> unbanip <IP>`
#  A list of commands can be found here: https://www.fail2ban.org/wiki/index.php/Commands
- name: Prepare all Fail2Ban configurations
  block:
    - name: Add the 'jail.local' configuration
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/linuxserver/docker-swag/refs/heads/master/root/defaults/fail2ban/jail.local
        dest: "{{ swag_volume_fail2ban }}/jail.local"
        mode: '0640'
    - name: Create 'filter.d' directory, which may be missing
      ansible.builtin.file:
        path: "{{ swag_volume_fail2ban }}/filter.d"
        state: directory
        owner: "{{ guid }}"
        group: "{{ guid }}"
        mode: "0755"
    - name: Add the 'cloudflare-token.local' configuration
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/fail2ban/fail2ban/refs/heads/master/config/action.d/cloudflare-token.conf
        dest: "{{ swag_volume_fail2ban }}/action.d/cloudflare-token.local"
        mode: '0640'
      when: swag_cloudflare_tunnel_enable | default(False)
    - name: Add Cloudflare Zone to 'clouflare-token.local'
      ansible.builtin.lineinfile:
        path: "{{ swag_volume_fail2ban }}/action.d/cloudflare-token.local"
        regexp: "{{ item[0] }}"
        firstmatch: true
        line: "{{ item[1] }}"
        insertafter: \[DEFAULT\]
        owner: "{{ guid }}"
        group: "{{ guid }}"
        mode: '0640'
      loop:
        - ["cfzone =", "cfzone = {{ cloudflare_zone_id[site_url] }}"]
        - ["cftoken =", "cftoken ="]  # remove # comment, if present.
      when: swag_cloudflare_tunnel_enable | default(False)
    - name: Select services for which 'fail2ban.yml' is available
      ansible.builtin.set_fact:
        fail2ban_services: "{{ fail2ban_services | default([]) + [item] }}"
      loop: "{{ containers }}"
      when: "lookup('ansible.builtin.fileglob', 'roles/' + item + '/tasks/fail2ban.yml', wantlist=True) | length == 1"
    - name: Include selected `fail2ban_services` roles and execute 'fail2ban' tasks
      ansible.builtin.include_role:
        name: "{{ item }}"
        tasks_from: fail2ban
      loop: "{{ fail2ban_services | default([]) }}"
    - name: Add options to 'jail.local'
      ansible.builtin.lineinfile:
        path: "{{ swag_volume_fail2ban }}/jail.local"
        regexp: "{{ item[0] }}"
        firstmatch: true
        line: "{{ item[1] }}"
        insertafter: \[DEFAULT\]
        owner: "{{ guid }}"
        group: "{{ guid }}"
        mode: '0640'
      loop:
        - ["^bantime", "bantime = 3600"]
        - ["^maxretry", "maxretry = 3"]

- name: Make sure that SWAG container is created and running
  community.docker.docker_container:
    name: "{{ swag_container_name }}"
    image: lscr.io/linuxserver/swag:latest
    pull: true
    networks:
      - name: "{{ swag_network_name }}"
    etc_hosts: "{{ [{'key': site_url, 'value': '127.0.0.1'}] | items2dict }}"
    capabilities:
      - net_admin
    state: started
    env: "{{ swag_container_env_vars }}"
    ports: "{{ swag_container_ports }}"
    volumes: "{{ swag_container_volumes }}"
    restart_policy: unless-stopped

- name: Attach Swag to the network of each container
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: network
  loop: "{{ containers | reject('equalto', 'socket_proxy') | reject('equalto', 'watchtower') | reject('equalto', 'onlyoffice') }}"

- name: Pause for 10 seconds and let SWAG creating configuration files
  ansible.builtin.pause:
    seconds: 10

- name: Enable optional additional headers in 'ssl.conf'
  ansible.builtin.replace:
    path: "{{ swag_volume_nginx }}/ssl.conf"
    regexp: "{{ item[0] }}"
    replace: "{{ item[1] }}"
  loop:
    - ["#add_header X-Content-Type-Options", "add_header X-Content-Type-Options"]
    - ["#add_header X-Frame-Options", "add_header X-Frame-Options"]
    - ["#add_header X-XSS-Protection", "add_header X-XSS-Protection"]
    - ["#add_header Referrer-Policy", "add_header Referrer-Policy"]
    - ["#add_header Strict-Transport-Security", "add_header Strict-Transport-Security"]
  notify:
    - Restart SWAG

- name: Custom error page
  block:
    - name: Create the necessary SWAG folder
      ansible.builtin.file:
        path: "{{ swag_volume_nginx }}/pages"
        state: directory
        owner: "{{ guid }}"
        group: "{{ guid }}"
        mode: "0750"
    - name: Copy the custom 403/404 error page
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ swag_volume_nginx }}/pages/{{ item }}"
        owner: "{{ guid }}"
        group: "{{ guid }}"
        mode: "0644"
      loop:
        - 403.html
        - 404.html
        - 5xx.html
    - name: Copy the error config
      ansible.builtin.copy:
        src: errors.conf
        dest: "{{ swag_volume_nginx }}/errors.conf"
        owner: "{{ guid }}"
        group: "{{ guid }}"
        mode: "0644"

- name: Update Maxmind configuration
  become: true
  when: swag_maxmind_enable | default(False)
  notify:
    - Restart SWAG
  block:
    - name: Customize 'maxmind.conf'
      ansible.builtin.template:
        src: nginx/maxmind.conf.j2
        dest: "{{ docker_dir }}/{{ swag_container_name }}/nginx/maxmind.conf"
        owner: "{{ guid }}"
        group: "{{ guid }}"
        mode: "0644"
    - name: Apply 'maxmind.conf to proxied services'
      ansible.builtin.lineinfile:
        path: "{{ docker_dir }}/{{ swag_container_name }}/nginx/nginx.conf"
        search_string: "include /config/nginx/maxmind.conf;"
        insertafter: "http {"
        line: "    include /config/nginx/maxmind.conf;"
