---
- name: Make sure that swag_internal container is created and running
  docker_container:
    name: swag_internal
    image: ghcr.io/linuxserver/swag:latest
    pull: true
    networks:
      - name: swag_internal_network
    capabilities:
      - net_admin
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      URL: "{{ host_local }}"
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: "{{ cloudflare_email }}"
      PROPAGATION: "60"
      DOCKER_MODS: linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload
    ports:
      - 192.168.1.3:443:443
      - 192.168.1.3:80:80
    volumes:
      - "{{ docker_dir }}/swag/internal/nginx:/config/nginx"
      - "{{ docker_dir }}/swag/dns-conf:/config/dns-conf"
      - "{{ docker_dir }}/swag/letsencrypt:/config/etc/letsencrypt"
    restart_policy: unless-stopped
