---
- name: Create the proxy-conf folders
  file:
    path: "{{ docker_dir }}/swag/{{ item }}/nginx/proxy-confs/"
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  with_items:
    - internal

- name: Create the DNS conf folder
  file:
    path: "{{ docker_dir }}/swag/dns-conf"
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Install the DNS config file
  template:
    src: dns-conf/cloudflare.ini.j2
    dest: "{{ docker_dir }}/swag/dns-conf/cloudflare.ini"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
  notify:
    - Restart swag
