---
- name: Create the proxy-conf folders
  become: true
  file:
    path: "{{ docker_dir }}/swag/nginx/proxy-confs/"
    state: directory
    recurse: true
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create the DNS conf folder
  file:
    path: "{{ docker_dir }}/swag/dns-conf"
    state: directory
    recurse: true
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0750"

- name: Install the DNS config file
  template:
    src: dns-conf/cloudflare.ini.j2
    dest: "{{ docker_dir }}/swag/dns-conf/cloudflare.ini"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0600"
