---
swag_container_name: swag
swag_network_name: swag_network
swag_dashboard_url: https://dashboard.{{ site_url }}
swag_homer_category: system
swag_dashboard_name: "SWAG Dashboard"
swag_container_env_vars:
  PUID: "{{ guid }}"
  PGID: "{{ guid }}"
  TZ: "{{ timezone }}"
  URL: "{{ site_url }}"
  SUBDOMAINS: "wildcard"
  ONLY_SUBDOMAINS: "false"
  VALIDATION: dns
  DNSPLUGIN: cloudflare
  EMAIL: "{{ cloudflare_email }}"
  PROPAGATION: "60"
  DOCKER_MODS: "linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-reload"

swag_maxmind_allowed_countries:
  - "AT"
  - "BE"
  - "BG"
  - "HR"
  - "CY"
  - "CZ"
  - "DK"
  - "EE"
  - "FI"
  - "DE"
  - "GR"
  - "HU"
  - "IE"
  - "IT"
  - "LV"
  - "LT"
  - "LU"
  - "NL"
  - "PL"
  - "PT"
  - "RO"
  - "SK"
  - "SI"
  - "ES"
  - "SE"
  - "IS"
  - 'NO'
  - "CH"
  - "GB"
  - "US"

swag_maxmind_blocked_countries:
  - "CN"
  - "IR"
  - "RU"
