---
- name: Create the necessary {{ container_name }} folders
  file:
    path: "{{ docker_dir }}/{{ container_name }}/config/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure that Wireguard container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/wireguard"
    pull: yes
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities: 
      - net_admin
      - sys_module
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "SERVERURL": "{{ duckdns_domain }}"
      "INTERNAL_SUBNET": "{{ wireguard_subnet }}"
      "PEERS": "{{ ', '.join(wireguard_peers) }}"
      "PEERDNS": 192.168.1.2
#      "ALLOWEDIPS": "192.168.1.0/24,{{ '.'.join(wireguard_subnet.split('.')[0:3]) }}.1"
      "ALLOWEDIPS": "0.0.0.0/0"
    ports:
      - "192.168.1.4:51820/udp:51820/udp"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "/lib/modules:/lib/modules"
    restart_policy: unless-stopped