---
- name: Create the MySQL data folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ seafile_container_name }}/mysql"
    state: directory
    owner: "999"
    group: "999"

- name: Create the Seafile data folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ seafile_container_name }}/seafile"
    state: directory
    owner: root
    group: root

- name: Create the SeaSearch data folder
  when: "'seasearch.yml' in seafile_compose_files"
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ seafile_container_name }}/seasearch"
    state: directory
    owner: root
    group: root

- name: Copy compose files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ docker_dir }}/{{ seafile_container_name }}/{{ item }}"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0600"
  loop: "{{ seafile_compose_files + ['.env'] }}"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Install ONLYOFFICE for document integration
  when: '"onlyoffice" in containers'
  ansible.builtin.include_role:
    name: onlyoffice
  vars:
    onlyoffice_network_name: "{{ seafile_network_name }}"
    onlyoffice_document_server_domain: "https://{{ seafile_subdomain }}.{{ site_url }}"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_name: "{{ seafile_container_name }}"
    project_src: "{{ docker_dir }}/{{ seafile_container_name }}"
    files: "{{ seafile_compose_files }}"
  ignore_errors: true

# For some reason, configuration files get overwritten and need to be re-created here
- name: Install Seafile config files
  ansible.builtin.template:
    src: "conf/{{ item }}.j2"
    dest: "{{ docker_dir }}/{{ seafile_container_name }}/seafile/seafile/conf/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  loop:
    - seafile.conf
    - gunicorn.conf.py
    - seafdav.conf
    - seafevents.conf
    - seahub_settings.py
  register: seafile_config_results

- name: Add a storage classes file
  ansible.builtin.copy:
    dest: "{{ docker_dir }}/{{ seafile_container_name }}/seafile/seafile/conf/seafile_storage_classes.json"
    content: |
      [
        {
          "storage_id": "local_storage",
          "name": "Local Storage",
          "is_default": true,
          "fs": {
            "backend": "fs",
            "dir": "/shared/seafile/seafile-data"
          },
          "commits": {
            "backend": "fs",
            "dir": "/shared/seafile/seafile-data"
          },
          "blocks": {
            "backend": "fs",
            "dir": "/shared/seafile/seafile-data"
          }
        },
        {
          "storage_id": "remote_storage",
          "name": "Remote Storage",
          "is_default": false,
          "commits": {
            "backend": "s3",
            "host": "{{ seafile_s3_endpoint }}",
            "aws_region": "{{ seafile_s3_region }}",
            "use_https": true,
            "use_v4_signature": true,
            "bucket": "{{ seafile_s3_commit_bucket }}",
            "sse_c_key": "{{ seafile_s3_sse_c_key }}",
            "key": "{{ seafile_s3_secret_key }}",
            "key_id": "{{ seafile_s3_key_id }}"
          },
          "fs": {
            "backend": "s3",
            "host": "{{ seafile_s3_endpoint }}",
            "aws_region": "{{ seafile_s3_region }}",
            "use_https": true,
            "use_v4_signature": true,
            "bucket": "{{ seafile_s3_fs_bucket }}",
            "sse_c_key": "{{ seafile_s3_sse_c_key }}",
            "key": "{{ seafile_s3_secret_key }}",
            "key_id": "{{ seafile_s3_key_id }}"
          },
          "blocks": {
            "backend": "s3",
            "host": "{{ seafile_s3_endpoint }}",
            "aws_region": "{{ seafile_s3_region }}",
            "use_https": true,
            "use_v4_signature": true,
            "bucket": "{{ seafile_s3_block_bucket }}",
            "sse_c_key": "{{ seafile_s3_sse_c_key }}",
            "key": "{{ seafile_s3_secret_key }}",
            "key_id": "{{ seafile_s3_key_id }}"
          }
        }
      ]
    owner: root
    group: root
    mode: "0600"

- name: Restart Seafile services
  when: seafile_config_results.changed
  community.docker.docker_compose_v2:
    project_src: "{{ docker_dir }}/{{ seafile_container_name }}"
    files: "{{ seafile_compose_files }}"
    state: restarted

- name: Install the SWAG config files
  template:
    src: "templates/{{ seafile_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ seafile_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
