---
- name: Create the icons folder
  file:
    path: "{{ docker_dir }}/homer/tools/homer-icons"
    state: directory
    mode: "0755"
    owner: "{{ guid }}"
    group: "{{ guid }}"

- name: Copy the icons
  copy:
    src: files/icons/{{ item['name'] }}.png
    dest: "{{ docker_dir }}/homer/tools/homer-icons"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
  when: item['url'] is defined
  loop: "{{ web_applications }}"

- name: Copy the icons for other dashboard elements
  copy:
    src: files/icons/{{ item }}
    dest: "{{ docker_dir }}/homer/tools/homer-icons"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
  loop:
    - logo.png
    - pihole.png
    - linuxserver.png

- name: Copy the custom stylesheet
  copy:
    src: files/custom.css
    dest: "{{ docker_dir }}/homer"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Generate the Homer config file
  template:
    src: config.yml.j2
    dest: "{{ docker_dir }}/homer/config.yml"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
