---
- name: Create the icons folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/homer/tools/homer-icons"
    state: directory
    mode: "0755"
    owner: "{{ guid }}"
    group: "{{ guid }}"

- name: Copy the icons
  ansible.builtin.copy:
    src: files/icons/{{ item['logo'] | basename }}
    dest: "{{ docker_dir }}/homer/tools/homer-icons"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
  when: item['url'] is defined
  loop: "{{ dashboard_apps }}"

- name: Copy the icons for other dashboard elements
  ansible.builtin.copy:
    src: files/icons/{{ item }}
    dest: "{{ docker_dir }}/homer/tools/homer-icons"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
  loop:
    - logo.png
    - pihole.png
    - linuxserver.png

- name: Copy the custom stylesheet
  ansible.builtin.copy:
    src: files/custom.css
    dest: "{{ docker_dir }}/homer"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Generate the Homer config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ docker_dir }}/homer/config.yml"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
  vars:
    colors: "{{ lookup('vars', colorscheme | lower + '_colors') }}"
