---
- name: Create the necessary folder
  file:
    path: "{{ docker_dir }}/homer"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

# https://github.com/bastienwirtz/homer
- name: Make sure that Homer container is created and running
  community.docker.docker_container:
    name: "{{ homer_container_name }}"
    image: b4bz/homer:latest
    pull: true
    networks:
      - name: "{{ homer_network_name }}"
    state: started
    user: "{{ guid }}:{{ guid }}"
    volumes:
      - "{{ docker_dir }}/homer:/www/assets"
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "Homer"
      swag.uptime-kuma.monitor.url: "{{ site_url }}"

- name: Install the Homer config files
  template:
    src: homer.subdomain.conf.j2
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/homer.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"

- name: Setup backup cron job
  ansible.builtin.include_tasks: tasks/backup_service.yml
  vars:
    service_name: "{{ homer_container_name }}"
    cron_schedule: "0 5 * * *"
    backup_cli_args:
      source_paths: "{{ docker_dir }}/{{ homer_container_name }}"
      destination_path: "{{ mergerfs_root }}/docker-volumes-backup"
      container_names_str: "{{ homer_container_name }}"
