---
# https://github.com/bastienwirtz/homer
- name: Make sure that Homer container is created and running
  docker_container:
    name: homer
    image: b4bz/homer
    pull: true
    networks:
      - name: swag_internal_network
    state: started
    user: "{{ guid }}:{{ guid }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/www/assets"
    restart_policy: unless-stopped

- name: Make sure cors-container is created and running
  docker_container:
    name: cors-container
    image: imjacobclark/cors-container
    pull: true
    networks:
      - name: swag_internal_network
    state: started
    restart_policy: unless-stopped
