---
- name: List services
  include_tasks: tasks/list_services.yml

- name: Set xresources
  include_tasks: xresources.yml

- name: Copy icons and other themes
  include_tasks: assets.yml

- name: Create and run docker container
  include_tasks: docker.yml
