---
- name: Install the Xresources file
  copy:
    dest: /home/{{ username }}/.Xresources
    src: files/colorschemes/{{ colorscheme | lower }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
