---
- name: Create the necessary Speedtest Tracker database
  file:
    path: "{{ docker_dir }}/{{ speedtest_tracker_container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Make sure that speedtest_tracker-mariadb container is created and running
  docker_container:
    name: "{{ speedtest_tracker_container_name }}-db"
    image: linuxserver/mariadb
    pull: true
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: speedtest
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    networks:
      - name: swag_network
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/{{ speedtest_tracker_container_name }}/data:/config"

- name: Make sure that Speedtest tracker container is created and running
  docker_container:
    name: "{{ speedtest_tracker_container_name }}"
    image: lscr.io/linuxserver/speedtest-tracker:latest
    pull: true
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      APP_KEY: "{{ speedtest_tracker_app_key }}"
      APP_URL: "{{ speedtest_tracker_dashboard_url }}"
      APP_TIMEZONE: "{{ timezone }}"
      DB_CONNECTION: mysql
      DB_HOST: "{{ speedtest_tracker_container_name }}-db"
      DB_DATABASE: speedtest
      DB_USERNAME: "{{ mysql_user }}"
      DB_PASSWORD: "{{ mysql_password }}"
      DISPLAY_TIMEZONE: "{{ timezone }}"
      SPEEDTEST_PING_URL: "1.1.1.1"
      SPEEDTEST_SCHEDULE: "0,10,20,30,40,50 * * * *"
      PRUNE_RESULTS_OLDER_THAN: "30"
    networks:
      - name: swag_network
    links:
      - "{{ speedtest_tracker_container_name }}-db"
    state: started
    restart_policy: unless-stopped
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "{{ speedtest_tracker_dashboard_name }}"
      swag.uptime-kuma.monitor.url: "{{ speedtest_tracker_dashboard_url }}"

- name: Install the SWAG config files
  template:
    src: "speedtest.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/speedtest.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
