---
- name: Create a docker network
  community.docker.docker_network:
    name: "{{ speedtest_tracker_network_name }}"
    connected:
      - "{{ swag_container_name }}"
    appends: true  # not necessary
