# References:
#  * https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker
#  * https://hub.docker.com/r/automaticrippingmachine/automatic-ripping-machine
#
# Noes:
# Run `lsscsi -g`, identify optical device and mount both sr/sg
---
- name: Create the necessary {{ container_name }} folder
  file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: 0755

- name: Copy the main ARM config
  copy:
    src: roles/containers/media/arm/templates/arm.yaml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/config/arm.yaml"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: 0644

- name: Copy HandBrake custom presets
  copy:
    src: roles/containers/media/arm/templates/handbrake-presets/HQ-576p-x264-crf20.json.j2
    dest: "{{ docker_dir }}/{{ container_name }}/config/HQ-576p-x264-crf20.json"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: 0644

- name: Make sure that {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "automaticrippingmachine/automatic-ripping-machine:latest"
    pull: yes
    networks:
      - name: swag_internal_network
    privileged: yes
    devices:
      - "/dev/sr0:/dev/sr0"
      - "/dev/sg0:/dev/sg0"
    state: "started"
    env:
      "ARM_UID": "{{ guid }}"
      "ARM_GID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/etc/arm/config"
      - "{{ docker_dir }}/{{ container_name }}/db:/home/arm/db"
      - "{{ cache_root }}/Downloads/arm_raw:/home/arm/media/raw"
      - "{{ cache_root }}/Downloads/arm_transcode:/home/arm/media/transcode"
      - "{{ mergerfs_root }}/Downloads/arm_completed:/home/arm/media/completed"
      - "{{ mergerfs_root }}/Downloads/arm_music:/home/arm/Music"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
