---
# First, deploy NextCloud. In this way, the proxy https://nextcloud.example.com/editors.

- name: Create necessary folders
  ansible.builtin.file:
    path: "{{ docker_dir }}/onlyoffice/DocumentServer/{{ item }}"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"
  loop:
    - data
    - db
    - lib
    - logs

- name: Make sure that ONLYOFFICE container is created and running
  docker_container:
    name: "{{ onlyoffice_container_name }}"
    image: onlyoffice/documentserver:8.1
    pull: true
    networks:
      - name: swag_network
    state: started
    env:
      JWT_ENABLED: "true"
      JWT_SECRET: "{{ onlyoffice_jwt_secret }}"
      JWT_HEADER: AuthorizationJwt
      USE_UNAUTHORIZED_STORAGE: "true"
    volumes:
      - "{{ docker_dir }}/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data"
      - "{{ docker_dir }}/onlyoffice/DocumentServer/db:/var/lib/postgresql"
      - "{{ docker_dir }}/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice"
      - "{{ docker_dir }}/onlyoffice/DocumentServer/logs:/var/log/onlyoffice"
    restart_policy: unless-stopped
