---
- name: Create the configuration directory
  file:
    path: "{{ docker_dir }}/{{ container_name }}/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Install the configuration template
  template:
    src: configuration.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/configuration.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
  register: configuration

- name: Install the users template
  template:
    src: users_database.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/users_database.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
  register: users

- name: Make sure that {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: authelia/authelia:latest
    pull: true
    networks:
      - name: swag_public_network
    state: started
    env:
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
    restart_policy: unless-stopped
  register: container

- name: Restart the docker container on change
  docker_container:
    name: "{{ container_name }}"
    restart: true
  when: container.changed or configuration.changed or users.changed
