---
- name: Create docker network
  ansible.builtin.include_tasks:
    file: network.yml

- name: Install vLLM container
  community.docker.docker_container:
    name: "{{ vllm_container_name }}"
    image: docker.io/vllm/vllm-openai:latest
    pull: true
    exposed_ports:
      - "8000"
    networks:
      - name: "{{ vllm_network_name }}"
    state: started
    env:
      HUGGING_FACE_HUB_TOKEN: "{{ hugging_face_token }}"
      DO_NOT_TRACK: "1"
      VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS: "1"
    volumes:
      - "{{ cache_root }}/docker-volumes-cache/{{ vllm_container_name }}:/root/.cache"
      - /etc/localtime:/etc/localtime:ro
    command: >
      "{{ vllm_default_model }}"
      --gpu-memory-utilization 0.65
      --enable-sleep-mode
      --max-model-len 262144
      --tensor-parallel-size 1
      --max-num-seqs 1
      --kv-cache-dtype fp8
      --enable-prefix-caching
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --language-model-only
      --default-chat-template-kwargs '{"enable_thinking": false}'
      --speculative-config '{"method": "mtp", "num_speculative_tokens": 3}'
    ipc_mode: host
    shm_size: 16G
    device_requests:
      - driver: nvidia
        count: -1
        capabilities: gpu
    runtime: nvidia
    restart_policy: unless-stopped

- name: Install the SWAG config files
  template:
    src: "{{ vllm_container_name }}.subdomain.conf.j2"
    dest: "{{ docker_dir }}/swag/nginx/proxy-confs/{{ vllm_container_name }}.subdomain.conf"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0644"
