---
- name: Restart SWAG
  community.docker.docker_container:
    name: "{{ swag_container_name }}"
    state: started
    restart: true

- name: Recreate SWAG
  community.docker.docker_container:
    name: "{{ swag_container_name }}"
    state: started
    recreate: true

- name: Refresh Uptime Kuma monitored services
  community.docker.docker_container_exec:
    container: "{{ swag_container_name }}"
    command: python3 /app/auto-uptime-kuma.py
