---
- name: Restart swag
  community.docker.docker_container:
    name: swag
    state: started
    restart: true

- name: Refresh Uptime Kuma monitored services
  community.docker.docker_container_exec:
    container: "{{ swag_container_name }}"
    command: python3 /app/auto-uptime-kuma.py
