# See here for hardware capabilities https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video
# 1. Verify which pkg is required (intel-media or i965), see Arch Wiki: https://wiki.archlinux.org/title/Hardware_video_acceleration
# 2. Bind `/dev/dri/card0` and `/dev/dri/renderD128`
# 3. Add the hw render group. `cat /etc/group | grep render`
# 4. If relying on old i965, purge `intel-media-*` in the container via `docker exec`.
# Bonus. Enable GuC and HuC: https://gist.github.com/Brainiarc7/aa43570f512906e882ad6cdd835efe57
---
- name: Make sure that QuickSync packages are installed
  become: true
  package:
    name:
      - vainfo
      - intel-media-va-driver-non-free
      - intel-gpu-tools
    state: present

- name: Make sure that {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: ghcr.io/linuxserver/jellyfin:latest
    pull: true
    networks:
      - name: swag_internal_network
    privileged: true
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    state: started
    #    healthcheck:  # it doesn't work :-(
    #      "test": ["CMD", "curl", "--fail", "http://jellyfin::8096/health", "||", "exit", "1"]
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      UMASK: "002"
      TZ: "{{ timezone }}"
      VERSION: latest
      JELLYFIN_PublishedServerUrl: https://jellyfin.{{ host_local }}
      DOCKER_MODS: linuxserver/mods:jellyfin-opencl-intel
    groups:
      - 109
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/Transcodes:/config/data/transcodes"
      - "{{ mergerfs_root }}/Media/Movies:/data/movies"
      - "{{ mergerfs_root }}/Media/TV:/data/tv"
      - "{{ mergerfs_root }}/Media/Books:/data/books:ro"
      - "{{ mergerfs_root }}/Media/Music:/data/music:ro"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: unless-stopped
