---
vllm_container_name: vllm
vllm_network_name: vllm_network
vllm_subdomain: vllm
vllm_server_url: https://{{ vllm_subdomain }}.{{ site_url }}
vllm_default_model: cyankiwi/Qwen3.5-9B-AWQ-4bit
vllm_grafana_url: https://{{ grafana_subdomain }}.{{ site_url }}/d/vllm-influxdb-dashboard
vllm_grafana_datasource: InfluxDB_v3_SQL
