---
# 1. Solve DNS and routing for the internal network "https://influxdb.catafal.co" or change to "http://127.0.0.1:8086".
# 2. Ensure the token is valid
# 3. Ensure configuration file is chmod 644

# If using Mosquitto as MQTT broker, note that by default it only listens to localhost.
# You can change this by adding next two lines in `/etc/mosquitto/mosquitto.conf`:
#  ```
#  allow_anonymous true
#  listener 1883
#  ```

- name: Add InfluxDB repository key
  ansible.builtin.deb822_repository:
    name: influxdb
    enabled: true
    types: deb
    uris: https://repos.influxdata.com/debian
    suites: stable
    components: main
    signed_by: https://repos.influxdata.com/influxdata-archive.key
    mode: '0644'

- name: Update repositories cache and install telegraf package
  ansible.builtin.apt:
    name: telegraf
    state: latest
    update_cache: true

- name: Save telegraf path
  command: which telegraf
  register: telegraf_path

- name: Set cap_sys_rawio,cap_dac_read_search,cap_sys_admin+ep on {{ telegraf_path.stdout }}
  community.general.capabilities:
    path: "{{ telegraf_path.stdout }}"
    capability: cap_sys_rawio,cap_dac_read_search,cap_sys_admin+ep
    state: present

- name: Copy the main telegraf config
  ansible.builtin.copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 644

- name: Copy the main telegraf config
  ansible.builtin.template:
    src: telegraf.j2
    dest: /etc/default/telegraf
    owner: root
    group: root
    mode: 644

- name: Add telegraf user to the docker group
  user:
    name: telegraf
    groups:
      - docker
      - sudo # this is required for SMART
    append: true

- name: Restart telegraf unit
  systemd:
    state: restarted
    daemon_reload: true
    name: telegraf
