# FIXME: Not really sure how to handle this programmatically.
#   1) Create a dedicated user to interact remotely with Calibre server
#      docker exec -i -u abc:abc calibreweb calibre-server --userdb /calibre/users.sqlite --manage-users
#   2) Start the server with proper arguments
#      docker exec -u abc:abc calibreweb calibre-server --enable-auth --enable-local-write --userdb /calibre/users.sqlite /books
#   3) Configure Readarr by specifying
---
- name: Create the necessary folder for Calibre-Web
  file:
    path: "{{ docker_dir }}/calibreweb/config"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create the Calibre folder
  file:
    path: "{{ docker_dir }}/calibreweb/calibre"
    state: directory
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Create the custom-services folder
  become: true
  file:
    path: "{{ docker_dir }}/calibreweb/custom-services.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy the users database
  copy:
    src: roles/calibreweb/files/users.sqlite
    dest: "{{ docker_dir }}/calibreweb/calibre/users.sqlite"
    owner: "{{ guid }}"
    group: "{{ guid }}"
    mode: "0755"

- name: Copy the launcher for Calibre server
  become: true
  copy:
    src: roles/calibreweb/templates/start-calibre.sh.j2
    dest: "{{ docker_dir }}/calibreweb/custom-services.d/start-calibre.sh"
    owner: root
    group: root
    mode: "0755"

- name: Add a crontab line to start Calibre webserver
  ansible.builtin.lineinfile:
    path: "{{ docker_dir }}/calibreweb/config/crontabs/abc"
    line: "@reboot calibre-server /books"
    create: true

- name: Make sure that Calibre-Web container is created and running
  docker_container:
    name: "calibreweb"
    image: lscr.io/linuxserver/calibre-web:latest
    pull: true
    networks:
      - name: swag_internal_network
    state: started
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      DOCKER_MODS: linuxserver/mods:universal-calibre|linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: wget
    volumes:
      - "{{ docker_dir }}/calibreweb/calibre:/calibre"
      - "{{ docker_dir }}/calibreweb/calibre/metadata.db:/books/metadata.db"
      - "{{ docker_dir }}/calibreweb/config:/config"
      - "{{ docker_dir }}/calibreweb/custom-services.d:/custom-services.d:ro"
      - "{{ mergerfs_root }}/Media/Books:/books"
    restart_policy: unless-stopped

- name: Install the SWAG config files
  template:
    src: calibreweb.subdomain.conf.j2
    dest: "{{ docker_dir }}/swag/internal/nginx/proxy-confs/calibreweb.subdomain.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

# TODO: create ad-hoc Docker exec commands for user creation and server start
